### ISSUE TITLE
1.3.2. Le sequenze

### ISSUE THREAD

**Issue by gollumone** [marco-buttu/pybook2nd#3]
Se proviamo a modificare un elemento di una stringa, otteniamo quindi un errore:

> > > mystring = 'python'
> > > mystring[0] = 'P'  # Vorremmo ottenere 'Python'
> > > Traceback (most recent call last):
> > >     ...
> > > TypeError: 'str' object does not support item assignment

Non possiamo modificarle, ma possiamo crearne di nuove. Ad esempio, se vogliamo ottenere la stringa 'Python' a partire da 'python', possiamo usare la concatenazione e lo slicing:

> > > 'P' + mystring[1:]
> > > 'Python'
# 

forse sarebbe il caso sottolineare, che non si  può cambiare una stringa, ma la si può riassegnare:

> > > mystring = 'python'
> > > print(mystring)
> > > python
> > > mystring = 'P' + mystring[1:]
> > > print(mystring)
> > > Python

cosa che non deve però trarre in inganno... (ma forse lo spiegherai nella parte delle stringhe, nel qual caso, non tener conto di questo commento).

Byez

**Comment by marco-buttu** [comment]
Ciao Mauro, parlo delle etichette e dell'effetto degli assegnamenti nel Capitolo 2. La' sara' chiaro che l'assegnamento:

`mystring = 'P' + mystring[1:]`

crea una nuova stringa, e la assegna all'etichetta `mystring`
